name = "juoksut"
pages_build_output_dir = "dist"
compatibility_date = "2025-03-09"

[[d1_databases]]
binding = "D1"
database_name = "juoksut-products"
database_id = "85dc51df-85fe-4b4a-871c-01a44a6e64b2"
preview_database_id = "test-juoksut-products"
